### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by bookercodes** [DevTips/Parallax-on-the-Web-DevTips-#11]
I kindly request that you make a live demo, ideally using [**GitHub pages**](https://pages.github.com/). I am curious to see the end-result.

**Comment by travisneilson** [comment]
Fantastic Idea!! Thank you!

**Comment by bookercodes** [comment]
I just watched the video - awesome!

And here is the [**link**](http://devtips.github.io/Parallax-on-the-Web-DevTips-/) for anyone who is interested :smile:
