### ISSUE TITLE
Path in Windows (local test)

### ISSUE THREAD

**Issue by sdhp** [DevTips/Parallax-on-the-Web-DevTips-#4]
Using the latest 0.3 Version on a Windows7 machine I had some trouble testing locally.
I figured out that I needed to change the paths to the img src's in index.html from 

src="/images/..." to 
src="images/... "

and in style.css the background-image urls to

background-image: url('../images/...

But now works like a charme as expected

Thx Travis

**Comment by hamzashezad** [comment]
I had the same problem in Ubuntu

**Comment by travisneilson** [comment]
Thanks for pointing this out, there are some pull requests that fix this issue ready to be accepted soon. I'm glad you are looking into these things for us! Keep on hacking!

**Comment by Amarkk** [comment]
Aku bukan hackers
